version: 1
disable_existing_loggers: False
formatters:
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(relative_pathname)s %(filename)s %(lineno)d %(message)s'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: XX_LOGFILE_PATH_XX  # Ensure this is replaced dynamically
    maxBytes: 10485760 # 10MB
    backupCount: 3
    encoding: utf8
loggers:
  '':
    level: INFO
    handlers: [file]
